-- Finance Hub database. Same tables and columns as the original SQLite file, so the queries port as-is.
-- Dates are ISO text ('YYYY-MM-DD'), money is double precision (Plaid sign: positive = money out).
--
-- Security: row-level security is ON for every table with no policies, so the public (anon) and
-- signed-in (authenticated) API roles can read nothing. Only the `api` edge function touches the data,
-- over a direct database connection, after checking that the caller is the owner.

create table items (
    item_id        text primary key,
    access_token   text not null,
    institution    text,
    env            text not null,
    products       text,
    cursor         text,
    status         text default 'ok',
    error          text,
    last_synced    text,
    linked_at      text
);
create table accounts (
    account_id     text primary key,
    item_id        text,
    source         text not null,          -- plaid | venmo | manual
    institution    text,
    name           text,
    mask           text,
    type           text,                   -- depository | investment | credit | loan | other
    subtype        text,
    balance        double precision,       -- current balance, positive number
    available      double precision,
    currency       text default 'USD',
    updated_at     text
);
create table transactions (
    txn_id         text primary key,
    account_id     text,
    date           text,
    name           text,
    amount         double precision,       -- positive = money out, negative = money in
    category       text,
    pending        integer default 0,
    detailed       text,
    raw_primary    text,
    source         text,                   -- plaid | plaid_inv | venmo | import
    txn_type       text,
    funding_source text,
    counterparty   text,
    seq            bigint generated always as identity  -- insertion order (SQLite's rowid); classify pairs in this order
);
create index transactions_account_date on transactions (account_id, date);
create index transactions_date on transactions (date);
create table holdings (
    account_id     text,
    security_id    text,
    ticker         text,
    name           text,
    quantity       double precision,
    price          double precision,
    value          double precision,
    cost_basis     double precision,
    primary key (account_id, security_id)
);
create table liabilities (
    account_id     text primary key,
    kind           text,
    apr            double precision,
    min_payment    double precision,
    next_due       text,
    last_statement double precision,
    extra          text
);
create table meta (
    key            text primary key,
    value          text
);
create table txn_overrides (
    txn_id         text primary key,
    flow           text,
    category       text,
    note           text,
    updated_at     text
);
create table rules (
    id             integer generated by default as identity primary key,
    pattern        text not null,
    account_id     text,
    direction      text,
    set_flow       text,
    set_category   text,
    created_at     text
);
create table txn_class (
    txn_id         text primary key,
    flow           text,
    kind           text,
    category       text,
    pair_id        text,
    review         integer default 0,
    reason         text
);
create table mortgage_alloc (
    txn_id         text primary key,
    extra          double precision
);
create table budgets (category text primary key, monthly double precision not null, updated_at text);
create table goals (
    id text primary key, type text not null, name text not null, target double precision, target_date text,
    config text, created_at text, archived integer default 0
);
create table goal_contribs (
    id integer generated by default as identity primary key, goal_id text not null, date text not null,
    amount double precision not null, note text, windfall_id text
);
create table windfalls (
    id text primary key, txn_id text, date text, label text, amount double precision, source text,
    status text default 'new', plan text, dismissed integer default 0
);
create table balance_snapshots (
    date           text,
    account_id     text,
    balance        double precision,
    cost_basis     double precision,
    primary key (date, account_id)
);

-- Sort and compare text byte by byte, the way SQLite does ('Roth' before 'individual'), so lists come out in
-- the same order as the original app.
do $$
declare r record;
begin
  for r in select table_name, column_name from information_schema.columns
           where table_schema = 'public' and data_type = 'text' loop
    execute format('alter table public.%I alter column %I type text collate "C"', r.table_name, r.column_name);
  end loop;
end $$;

do $$
declare t text;
begin
  foreach t in array array['items','accounts','transactions','holdings','liabilities','meta','txn_overrides',
    'rules','txn_class','mortgage_alloc','budgets','goals','goal_contribs','windfalls','balance_snapshots'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon, authenticated', t);
  end loop;
end $$;

-- SQLite's ROUND(real, n): Postgres only rounds numeric, so accept double precision too (half away from zero,
-- same as SQLite).
create function round(v double precision, n integer) returns double precision
  language sql immutable parallel safe as $$ select round(v::numeric, n)::double precision $$;
